name: _ Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Formatting
        run: dotnet format style

      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          config: ./typos.toml
